# == Configurations == #

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_project
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081

